# Array of source patch
sources = ["data/src/scripts/"]

# Array of symbol paths


# Whether to enable pointer checking. This adds additional safety but with a
# compile time cost.
check_pointers = true

# Binary file writer configuration
[writer.binary]

# The output path
output = "data/pack/server"