[package]
name = "worldlist"
version = "0.1.0"
edition = "2024"

[dependencies]
lazy_static = "1.5.0"
log = "0.4.27"
tokio = "1.45.1"
engine = { path = "../engine" }
env_logger = "0.11.8"
constants = { path = "../constants" }

